version: '3.8'
services:
  postgres-compose:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_PASSWORD: "123"
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network

  pgadmin-compose:
    image: dpage/pgadmin4:6.15
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "postgree"
    ports:
      - "15432:80"
    depends_on:
      - postgres-compose
    networks:
      - postgres-compose-network

  redis-compose:
    image: redis:latest
    tty: true
    command: sh -cx "redis-server --daemonize yes && redis-cli config set notify-keyspace-events KEA && sleep infinity"
    ports:
      - "6379:6379"
    networks:
      - postgres-compose-network

  redis-insight:
    image: redislabs/redisinsight:latest
    ports:
      - "8001:8001"
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge
